# yaml-language-server: $schema=node_modules/wrangler/config-schema.json
name = "rytmica-web"
main = "server/index.jsx"
compatibility_date = "2026-01-03"
compatibility_flags = ["nodejs_compat"]

# 静的アセット配信
[assets]
directory = "./public"

# ドメイン: mnc.ryuya-dev.net
